return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    opts.ensure_installed = require("astronvim.utils").list_insert_unique(opts.ensure_installed, {
      "po",
      "go",
      "vim",
      "lua",
      "css",
      "sql",
      "vue",
      "bash",
      "html",
      "json",
      "scss",
      "yaml",
      "regex",
      "jsdoc",
      "gomod",
      "gosum",
      "gowork",
      "markdown",
      "gitcommit",
      "gitignore",
      "git_config",
      "javascript",
      "typescript",
      "markdown_inline",
    })
  end,
}
